import os
from dotenv import load_dotenv

load_dotenv()

POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_SERVER = os.getenv("POSTGRES_SERVER")
DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_SERVER}:{POSTGRES_PORT}/{POSTGRES_DB}"
SCHEMA= os.getenv("SCHEMA")

SECRET_KEY= "lms_9f8aK2#pQ7!xT4zW@1vN6mR$8yHcD3s!"
ALGORITHM= "HS256"
TOKEN_EXPIRATION_TIME_MINUTES=15
REFRESH_TOKEN_EXPIRE_MINUTES =30